version: '3.8'
services:
    sqlserver:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        ports:
            - '1433:1433'
        deploy:
          resources:
            reservations:
              cpus: '2'
              memory: 2GB
        volumes:
            - sqldata:/var/opt/mssql
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
    webapp:
        ports:
            - '80:80'
        container_name: webapp
        restart: on-failure
        #build:
          #dockerfile: ./Dockerfile
        image: krastyocontactscr.azurecr.io/contacts
        domainname: krastyotodorov
volumes:
  sqldata:
    #external: true
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: krastyocontactsstorage
